export const uiText = {
  common: {
    appName: "PT NDS",
    appDesc: "Sistem Inventaris",
    developedBy: "Dikembangkan oleh rama",
    save: "Simpan",
    cancel: "Batal",
    close: "Tutup",
    loading: "Memuat...",
    error: "Terjadi kesalahan",
    noData: "Tidak ada data ditemukan.",
    comingSoon: "Segera Hadir",
    search: "Cari",
    reset: "Reset",
  },
  auth: {
    login: "Masuk",
    logout: "Keluar",
    usernameOrEmail: "Nama Pengguna atau Email",
    password: "Kata Sandi",
    signIn: "Masuk ke Akun",
    signInDesc: "Masukkan kredensial Anda untuk mengakses sistem inventaris.",
    invalidCreds: "Kredensial tidak valid",
  },
  nav: {
    dashboard: "Dasbor",
    masterItems: "Master Barang",
    transactions: "Transaksi",
    reports: "Laporan",
  },
  dashboard: {
    title: "Dasbor",
    desc: "Ringkasan tingkat stok saat ini.",
    fetchError: "Gagal memuat data inventaris. Silakan muat ulang halaman.",
    noDataDesc: "Belum ada barang dalam inventaris.",
    searchPlaceholder: "Cari barang...",
  },
  profile: {
    title: "Profil",
    desc: "Kelola akun dan kata sandi Anda.",
    accountInfo: "Informasi Akun",
    changePassword: "Ganti Kata Sandi",
    oldPassword: "Kata Sandi Lama",
    newPassword: "Kata Sandi Baru",
    confirmPassword: "Konfirmasi Kata Sandi Baru",
    savePassword: "Simpan Kata Sandi",
    changePasswordSuccess: "Kata sandi berhasil diperbarui.",
    passwordMismatch: "Konfirmasi kata sandi tidak cocok.",
    passwordTooShort: "Kata sandi baru minimal 6 karakter.",
  },
  items: {
    title: "Master Barang",
    desc: "Kelola barang inventaris dan kategori.",
    addItem: "Tambah Barang",
    addNewItem: "Tambah Barang Baru",
    saveItem: "Simpan Barang",
    addSuccess: "Barang berhasil ditambahkan.",
    fetchError: "Gagal memuat data barang. Silakan muat ulang halaman.",
    noDataDesc: "Belum ada barang yang ditambahkan. Klik 'Tambah Barang' untuk memulai.",
    id: "ID Barang",
    name: "Nama",
    category: "Kategori",
    stock: "Stok",
    unit: "Satuan",
    status: "Status",
    directEdit: "Edit Langsung",
    details: "Detail",
    allowed: "Diizinkan",
    forbidden: "Dilarang",
    volumePerCan: "Volume per Kaleng (Liter)",
    specification: "Spesifikasi",
  },
  transactions: {
    title: "Transaksi",
    desc: "Catat dan lihat pergerakan inventaris.",
    newTx: "Transaksi Baru",
    recordTx: "Catat Transaksi",
    saveTx: "Simpan Transaksi",
    saveSuccess: "Transaksi berhasil disimpan.",
    fetchError: "Gagal memuat data transaksi. Silakan muat ulang halaman.",
    noDataDesc: "Belum ada transaksi yang tercatat.",
    date: "Tanggal",
    item: "Barang",
    type: "Tipe",
    qty: "Kuantitas",
    physicalStockLabel: "Stok Fisik Aktual",
    user: "Pengguna / Kontraktor",
    ship: "Nama Kapal",
    notes: "Catatan",
    selectItem: "Pilih barang",
    stockIn: "Stok Masuk",
    stockOut: "Stok Keluar",
    exchange: "Tukar (Hanya Tabung)",
    adjustment: "Penyesuaian",
    directEdit: "Edit Langsung (Opname)",
    typeHints: {
      OUT: "Barang keluar untuk pemakaian.",
      IN: "Barang masuk ke gudang.",
      EXCHANGE: "Tukar tabung kosong dengan isi. Stok tidak berubah.",
      DIRECT_EDIT: "Penyesuaian stok berdasarkan fisik gudang (opname).",
      ADJUSTMENT: "Koreksi karena selisih, rusak, atau kesalahan pencatatan.",
    },
    qtyPerUnitHint: "Jumlah per satuan item.",
    physicalCountNote: "Masukkan jumlah fisik sebenarnya.",
    adjustmentNote: "Gunakan nilai koreksi positif atau negatif sesuai selisih.",
    userPlaceholder: "cth. DADANG, FAUZAN, MARLIS",
    photo: "Foto Dokumentasi",
    photoOptional: "Opsional untuk kategori/tipe transaksi ini.",
    signature: "Tanda Tangan",
    clearSignature: "Hapus Tanda Tangan",
    photoRequired: "Foto wajib diunggah untuk tabung.",
    signatureRequired: "Tanda tangan wajib untuk tabung.",
    itemRequired: "Barang wajib dipilih.",
    quantityInvalid: "Kuantitas wajib diisi dengan angka yang valid.",
    shipRequiredPaintOut: "Nama Kapal wajib diisi untuk transaksi Cat keluar.",
    shipRequiredOut: "Nama Kapal wajib diisi untuk transaksi keluar Cat dan Besi.",
    drawSignature: "Gambar tanda tangan di sini",
  },
  reports: {
    title: "Laporan",
    desc: "Hasilkan dan unduh laporan sistem.",
    exportSuccess: "PDF berhasil diunduh.",
    noDataDesc: "Tidak ada data yang cocok dengan filter yang dipilih.",
    steelNoFilterDesc: "Terapkan filter kapal dan kontraktor untuk melihat data penggunaan besi.",
    stockReport: "Laporan Stok Akhir",
    stockReportDesc: "Tingkat inventaris saat ini untuk semua barang termasuk tabung, cat, dan baja.",
    exportPdf: "Ekspor PDF",
    txHistory: "Riwayat Transaksi",
    txHistoryDesc: "Log detail semua pergerakan stok difilter berdasarkan tanggal dan barang.",
    paintUsage: "Penggunaan Cat",
    paintUsageDesc: "Laporan konsumsi cat diagregasi berdasarkan kapal.",
    steelUsage: "Penggunaan Besi",
    steelUsageDesc: "Laporan penggunaan besi berdasarkan kapal dan kontraktor.",
    viewReport: "Lihat Laporan",
    backToReports: "Kembali ke Laporan",
    filters: "Filter",
    applyFilter: "Terapkan Filter",
    resetFilter: "Reset",
    startDate: "Tanggal Mulai",
    endDate: "Tanggal Akhir",
    allCategories: "Semua Kategori",
    allTypes: "Semua Tipe",
    allItem: "Semua Barang",
    allShips: "Semua Kapal",
    allContractors: "Semua Kontraktor",
    contractor: "Kontraktor",
    selectShipToExport: "Pilih kapal terlebih dahulu untuk mengekspor PDF.",
    paintPdfExportFailed: "Gagal mengekspor PDF penggunaan cat.",
    selectSteelFiltersToExport: "Pilih kapal dan kontraktor terlebih dahulu untuk mengekspor PDF.",
    colDate: "Tanggal",
    colItem: "Item",
    colCategory: "Kategori",
    colType: "Tipe Transaksi",
    colQty: "Jumlah",
    colUnit: "Satuan",
    colUser: "Pengguna",
    colShip: "Kapal",
    colNotes: "Keterangan",
    colCat: "Cat",
    colTotalCans: "Total Kaleng",
    colTotalLiters: "Total Liter",
  },
  theme: {
    toggle: "Ganti Tema",
    light: "Terang",
    dark: "Gelap",
    system: "Sistem",
  }
};

export const categoryLabel: Record<string, string> = {
  CYLINDER: "TABUNG",
  PAINT: "CAT",
  STEEL: "BESI",
};

export const txTypeLabel: Record<string, string> = {
  IN: "Stok Masuk",
  OUT: "Stok Keluar",
  EXCHANGE: "Tukar",
  ADJUSTMENT: "Penyesuaian",
  DIRECT_EDIT: "Set Stok Awal",
};

export const statusLabel: Record<string, string> = {
  normal: "Normal",
  damaged: "Rusak",
  IN_STOCK: "IN STOCK",
  LOW_STOCK: "LOW STOCK",
  OUT_OF_STOCK: "OUT OF STOCK",
};
